### ISSUE TITLE
Will this ever work on a Surface Laptop Studio?

### ISSUE THREAD

**Issue by Hepi34** [Xiashangning/BigSurface#124]
I am using a Surface Laptop Studio, which has a theoretically unsupported iGPU (Iris XE). Despite this, I still got MacOS istalled and fully functioning. The only things which currently don't work are the keyboard and trackpad. I tried using this Kext and SSDT, but nothing changed. 

Is there a possibility that support for the SLS will be added? The SLS uses a SAM-module similair to the Surface Laptop 3 to control the keyboard and trackpad, so I believe it could be possible.

**Comment by jlempen** [comment]
> I am using a Surface Laptop Studio, which has a theoretically unsupported iGPU (Iris XE). 

The Iris XE is not "theoretically" unsupported, it is "totally" unsupported due to the lack of drivers on macOS and spoofing another iGPU such as the UHD 620 simply won't work. The last Intel Macs released by Apple were based on Intel's 10th Gen Ice Lake platform and those CPUs and iGPUs are the last ones which will ever be supported by macOS. So while spoofing the CPU is easily possible, spoofing newer Intel iGPUs than Gen 10 is impossible, as far as I know.

> Despite this, I still got MacOS istalled and fully functioning.

You got it working without graphics acceleration using the vesa drivers, which makes macOS pretty much totally unusable, the level of performance being more or less as terrible as on a VM. 

> Is there a possibility that support for the SLS will be added? The SLS uses a SAM-module similair to the Surface Laptop 3 to control the keyboard and trackpad, so I believe it could be possible.

So while in theory it would be possible to add support for the Surface Laptop Studio's keyboard/trackpad/touchscreen/battery (the USB camera should work out of the box), nobody is going to spend all this time and energy to add support for a device which is basically unsupported anyway, as nothing is working on macOS without graphics acceleration...
