### ISSUE TITLE
No battery/touchpad on BigSur

### ISSUE THREAD

**Issue by yummytutel** [Xiashangning/BigSurface#87]
Hello,
I've been using bigsur on the surface pro 4 and the battery and trackpad don't get recognized on macOS.
Any clue of what happened?

(The trackpad works but basic functionality)

**Comment by balopez83** [comment]
Hi @yummytutel , you can use my repo EFI which already has the correct settings for your computer. Yours is not working because you likely did not register the BigSurface kext correctly in your config.plist. 

See my link below for a pre-built Surface Pro 4 EFI
https://github.com/balopez83/Surface_Pro_4_and_Surface_Book_Hackintosh

Edit: The instructions are located on the main page which will walk you through any steps you need to get it fully running.
